name: Deploy my Lambda Function

on: [push]
  
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
      - name: Install libraries
        run: pip install flake8
      - name: Lint with flake8
        run:  |
            cd function
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
           
  build:           
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: 3.10.9
        - name: Install libraries
          run: pip install flake8
        - name: Lint with flake8
          run:  |
              cd function
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
        - name: Create zip bundle
          run:  |
              cd function
              zip -r ../${{ github.sha }}.zip .
        - name: Archive artifact
          uses: actions/upload-artifact@v3
          with:
            name: zipped-bundle
            path: ${{ github.sha }}.zip
          
  documentation: 
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: create docs folder
        run: mkdir docs
      - name: convert md to html
        uses: docker://pandoc/core:2.17
        with:
          args: userguide.md -t html -o docs/index.html
      - name: deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          
